name: R Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install dependencies inside R
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("covr")'
          Rscript -e 'install.packages("testthat")'  # Assuming testthat is being used for testing
          # Install other dependencies as required by your project

      # Run tests and collect coverage
      - name: Run tests and collect coverage
        run: |
          # Run tests with testthat
          Rscript -e 'devtools::test()'

          # Generate coverage report using covr
          Rscript -e '
          coverage <- covr::package_coverage(quiet = TRUE, clean = FALSE)
          print(coverage)

          # Show the coverage percentage
          coverage_percentage <- sum(coverage$covered) / sum(coverage$total) * 100
          cat("Test coverage percentage: ", coverage_percentage, "%\n")
          '
